name: Setup Python environment
description: Create venv and install dependencies from requirements.txt

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Create venv and install dependencies
      shell: bash
      run: |
        python -m venv .venv
        ./.venv/bin/python -m pip install --upgrade pip
        ./.venv/bin/python -m pip install -r requirements.txt
        ./.venv/bin/python -m pip install "robotpy[commands2]"
        ./.venv/bin/python -m pip install "phoenix6==26.70.0a2"
        ./.venv/bin/python -m pip install black==26.5.1
        ./.venv/bin/python -m pip install pyright
